### ISSUE TITLE
Add support to turn off unzip.

### ISSUE THREAD

**Issue by Etterna** [sevaa/githubactions#4]
At the moment any downloaded artefact will be unzipped. 
But there are some cases when I want to use that downloaded an artifact as is, not unzipping it. 
It would be good to have a property where I can set if I want to unzip it or not

**Comment by sevaa** [comment]
On which task? Or both?

**Comment by Etterna** [comment]
DownloadArtifacts

**Comment by sevaa** [comment]
Done, published. I've increased the major task version to 2, you'd need to update your definition.
