### ISSUE TITLE
The DownloadArtifacts task doesn't support azure pipelines service connection

### ISSUE THREAD

**Issue by Etterna** [sevaa/githubactions#5]
Currently, to download artifact from the GitHub we can use GitHub service connection with the **oauth** authentication method.
We provide the name of the service connection and the task successfully resolves it.

<img width="405" alt="Screenshot 2023-09-05 at 13 52 52" src="https://github.com/sevaa/githubactions/assets/8383928/df63b45d-a49b-4b4b-92ac-3fb5e13f07db">

But if the GitHub service connection is created using the Azure Pipelines integration app, the task fails to authenticate.

<img width="425" alt="Screenshot 2023-09-05 at 13 53 04" src="https://github.com/sevaa/githubactions/assets/8383928/d38b47ab-16ac-416b-99ae-09ad202d0e31">

<img width="1068" alt="Screenshot 2023-09-05 at 14 13 24" src="https://github.com/sevaa/githubactions/assets/8383928/7cad2e7d-f433-4b97-8639-5ca21a73ba39">

You can find the integration app here: https://github.com/marketplace/azure-pipelines
After installation and authorization in Azure DevOps, the service connection will be created automatically.

It would be great to support that GitHub service connection type.

**Comment by sevaa** [comment]
The expected service endpoint type is a part of the task parameter description in the manifest. To the best of my knowledge, there is no way to specify multiple types there.

Also, a workaround is trivially possible. Create another endpoint.

**Comment by sevaa** [comment]
According to Microsoft, this endpoint type is not supposed to be used in tasks: https://github.com/microsoft/azure-pipelines-tasks/issues/9394

That said, I'll dig some more.
